In [1]:
# install numpy 

# !pip install numpy

In [2]:
#import numpy
import numpy as np

In [3]:
# some operations using numpy



In [4]:
age_list=[23,28,11,18,34]

In [5]:
age_array =np.array(age_list)
age_array

array([23, 28, 11, 18, 34])

In [6]:
# checking the type of the variable
print(type(age_array))

<class 'numpy.ndarray'>


In [7]:
# shape of the array

print(age_array.shape)

(5,)


In [8]:
#create a array of books with prices

books=np.array([('learn python','data science journal','scala for data science'),(20,23,18)])
books





array([['learn python', 'data science journal', 'scala for data science'],
       ['20', '23', '18']], dtype='<U22')

In [9]:
# print no. of dimensions of the array

print ('no. of dimensions of the array',books.ndim)

no. of dimensions of the array 2


In [10]:
# for practice using for loop

for i in books :
 
    print(books)

[['learn python' 'data science journal' 'scala for data science']
 ['20' '23' '18']]
[['learn python' 'data science journal' 'scala for data science']
 ['20' '23' '18']]


In [11]:
# dimensions in array

brr = np.array([(3.3,4.2,5.7),(1.0,3.0,0.8)])

In [12]:
brr

array([[3.3, 4.2, 5.7],
       [1. , 3. , 0.8]])

In [13]:
brr.ndim

2

In [14]:
# numpy array attributes 
#shape
#size 
#dtype
#ndim

In [15]:
books

array([['learn python', 'data science journal', 'scala for data science'],
       ['20', '23', '18']], dtype='<U22')

In [16]:
books.ndim

2

In [17]:
brr

array([[3.3, 4.2, 5.7],
       [1. , 3. , 0.8]])

In [18]:
# print the no. of elements in the array

print(' the no. of elements in the array :',brr.size)

 the no. of elements in the array : 6


In [19]:
# print datadtype

print ('datadtype :',brr.dtype)

datadtype : float64


In [20]:
# print shape

print ('shape :',brr.shape)

shape : (2, 3)


In [21]:
# create 2d array of integers

arr=np.array([(33,18),(50,20),(40,34)])

In [22]:
print("created array : \n",arr)

created array : 
 [[33 18]
 [50 20]
 [40 34]]


In [23]:
print('shape :',arr.shape)
print('size :',arr.size)
print('dimensions :',arr.ndim)
print('datatype :',arr.dtype)

shape : (3, 2)
size : 6
dimensions : 2
datatype : int32


In [24]:
# array indexing and slicing

data_scientist = np.array([('vinayaka',18),('hruthik',20),('prem',30)])

In [25]:
print("the array :\n",data_scientist)

the array :
 [['vinayaka' '18']
 ['hruthik' '20']
 ['prem' '30']]


In [26]:
# print the last element using indexing 

print ('the last element is :',data_scientist[-1])

the last element is : ['prem' '30']


In [27]:
# retrive the age of prem 

print('age of the prem is :',data_scientist[-1][1])

age of the prem is : 30


In [28]:
"""the array operations listed below 

reshape
transpose
min
max
std
square
power
dot
addition
substraction
apppend 
size 
flatten
"""

'the array operations listed below \n\nreshape\ntranspose\nmin\nmax\nstd\nsquare\npower\ndot\naddition\nsubstraction\napppend \nsize \nflatten\n'

In [29]:
# different ways of creating array

# numpy.arrange (start,stop,step,dtype)

In [30]:
# use start and stop
crr= np.arange(start=10,stop=20)

In [31]:
crr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
# use step
crr= np.arange(start=10,stop=20,step=2)
crr


array([10, 12, 14, 16, 18])

In [33]:
import random


In [34]:
crr= random.randint(10,20)

In [35]:
crr

17

In [62]:
#pandas


In [64]:
# import pandas

import pandas as pd


In [39]:
# reading various file formats in pandas 
# csv files using read_csv() function

In [47]:
import pandas as pd

df = pd.read_csv('heroes_information.csv')


FileNotFoundError: [Errno 2] No such file or directory: 'heroes_information.csv'

In [41]:
df=pd.read_csv('mobile_dataset1.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'mobile_dataset1.csv'